# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('interests', models.CharField(default='', max_length=3200)),
                ('Events', models.CharField(default='', max_length=3200)),
                ('Blog', models.CharField(default='', max_length=3200)),
                ('Members', models.CharField(default='', max_length=3200)),
                ('contactEmail', models.EmailField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=3200)),
                ('oneliner', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='eve_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('Club_Name', models.CharField(default='Unknown Club', max_length=32)),
                ('Description', models.CharField(default='', max_length=6000, null=True)),
                ('UserRegistered', models.CharField(default='', max_length=3200)),
                ('Email', models.EmailField(max_length=32)),
                ('Venue', models.CharField(max_length=32)),
                ('poster', models.ImageField(blank=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Conversation Date')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Conversation Time')),
                ('HostSpeakers', models.CharField(default='', max_length=100, null=True)),
                ('interests', models.CharField(default='', max_length=3200)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=32)),
                ('Name', models.CharField(max_length=45)),
                ('Password', models.CharField(max_length=32)),
                ('interests', models.CharField(default='', max_length=3200)),
                ('Registered_Events', models.CharField(default='', max_length=3200)),
                ('cl_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag_Name', models.CharField(max_length=32)),
                ('Club_Linked', models.CharField(default='', max_length=3200)),
                ('UserSubscribed', models.CharField(default='', max_length=3200)),
            ],
        ),
    ]
